import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts";
import Providers from "@/providers/redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
